export const brandAssets = {
  logo: "/brand/logo-official.png",
  logoPremium: "/brand/logo-download-gold.png",
  monogramLight: "/brand/monogram-download-black.png",
  socialPreview: "/brand/logo-download-gold.png",
  media: {
    instituteSpaceWide: "/media/institute-space-wide.jpeg",
    instituteSpaceFront: "/media/institute-space-front.jpeg",
    instituteSpaceDesk: "/media/institute-space-desk.jpeg",
    founderHangarElite: "/media/founder-hangar-elite.jpg",
    founderSeripaLecture: "/media/founder-seripa-lecture.jpg",
    founderKeynoteHeic: "/media/founder-keynote-heic.jpg",
    simulatorAviation: "/media/simulator-aviation.jpg",
    cockpitSimulator: "/media/cockpit-simulator.jpg",
    institutionalPortrait: "/media/institutional-portrait.jpg",
    aviationTalk: "/media/aviation-talk.jpg",
    hangarOperations: "/media/hangar-operations.jpg",
    founderCenipa: "/media/founder-cenipa.jpg",
    founderExecutive: "/media/founder-executive.jpg",
    founderStageBlue: "/media/founder-stage-blue.jpg",
    founderStageRoom: "/media/founder-stage-room.jpg",
    founderAviationKeynote: "/media/founder-aviation-keynote.jpg",
    founderAviationCeremony: "/media/founder-aviation-ceremony.jpg",
    founderCongressDownload: "/media/founder-congress-download.jpg",
    founderHangarAircraft: "/media/founder-hangar-aircraft.jpg",
    founderSeripaAuditorium: "/media/founder-seripa-auditorium.jpg",
    founderAeteKeynote: "/media/founder-aete-keynote.png",
    founderHangarCommand: "/media/founder-hangar-command.jpg",
    founderOperationalBriefing: "/media/founder-operational-briefing.jpg",
    founderBriefingStage: "/media/founder-briefing-stage.jpg",
    founderBriefingStageAlt: "/media/founder-briefing-stage-2.png",
    formationTrainingApplied: "/media/formacao-training-applied.jpg",
    formationControlledEnvironment: "/media/formacao-controlled-environment.jpg",
    formationInstitutionalPoster: "/media/formacao-institucional-poster.jpg"
  },
  videos: {
    institutionalHero: "/media/institucional-hero.mov",
    instituteSignature: "/media/instituto-signature.mp4",
    formationOperational: "/media/formacao-operacional.mp4",
    formationInstitutional: "/media/formacao-institucional.mp4"
  }
} as const;
